# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: _tensorflow_core/graph.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from _tensorflow_core import node_def_pb2 as __tensorflow__core_dot_node__def__pb2
from _tensorflow_core import function_pb2 as __tensorflow__core_dot_function__pb2
from _tensorflow_core import versions_pb2 as __tensorflow__core_dot_versions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='_tensorflow_core/graph.proto',
  package='_tensorflow',
  syntax='proto3',
  serialized_pb=_b('\n\x1c_tensorflow_core/graph.proto\x12\x0b_tensorflow\x1a\x1f_tensorflow_core/node_def.proto\x1a\x1f_tensorflow_core/function.proto\x1a\x1f_tensorflow_core/versions.proto\"\xa0\x01\n\x08GraphDef\x12\"\n\x04node\x18\x01 \x03(\x0b\x32\x14._tensorflow.NodeDef\x12)\n\x08versions\x18\x04 \x01(\x0b\x32\x17._tensorflow.VersionDef\x12\x13\n\x07version\x18\x03 \x01(\x05\x42\x02\x18\x01\x12\x30\n\x07library\x18\x02 \x01(\x0b\x32\x1f._tensorflow.FunctionDefLibraryB,\n\x18org.tensorflow.frameworkB\x0bGraphProtosP\x01\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[__tensorflow__core_dot_node__def__pb2.DESCRIPTOR,__tensorflow__core_dot_function__pb2.DESCRIPTOR,__tensorflow__core_dot_versions__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GRAPHDEF = _descriptor.Descriptor(
  name='GraphDef',
  full_name='_tensorflow.GraphDef',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='_tensorflow.GraphDef.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='versions', full_name='_tensorflow.GraphDef.versions', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='_tensorflow.GraphDef.version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='library', full_name='_tensorflow.GraphDef.library', index=3,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=305,
)

_GRAPHDEF.fields_by_name['node'].message_type = __tensorflow__core_dot_node__def__pb2._NODEDEF
_GRAPHDEF.fields_by_name['versions'].message_type = __tensorflow__core_dot_versions__pb2._VERSIONDEF
_GRAPHDEF.fields_by_name['library'].message_type = __tensorflow__core_dot_function__pb2._FUNCTIONDEFLIBRARY
DESCRIPTOR.message_types_by_name['GraphDef'] = _GRAPHDEF

GraphDef = _reflection.GeneratedProtocolMessageType('GraphDef', (_message.Message,), dict(
  DESCRIPTOR = _GRAPHDEF,
  __module__ = '_tensorflow_core.graph_pb2'
  # @@protoc_insertion_point(class_scope:_tensorflow.GraphDef)
  ))
_sym_db.RegisterMessage(GraphDef)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030org.tensorflow.frameworkB\013GraphProtosP\001\370\001\001'))
_GRAPHDEF.fields_by_name['version'].has_options = True
_GRAPHDEF.fields_by_name['version']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
